from __future__ import annotations

SOURCE_PROVENANCE_LEGACY = "legacy"
SOURCE_PROVENANCE_ADMIN_UPLOAD = "admin_upload"
SOURCE_PROVENANCE_EXTERNAL_URL = "external_url"
SOURCE_PROVENANCE_EVALUATION_FIXTURE = "evaluation_fixture"

SOURCE_TRUST_TRUSTED = "trusted"
SOURCE_TRUST_EXTERNAL_UNTRUSTED = "external_untrusted"

SECURITY_REVIEW_PENDING = "pending"
SECURITY_REVIEW_APPROVED = "approved"
SECURITY_REVIEW_QUARANTINED = "quarantined"

SECURITY_REVIEW_REASON_ADMIN_PASSED = "admin_review_passed"
SECURITY_REVIEW_REASON_PROMPT_INJECTION = "prompt_injection_detected"
SECURITY_REVIEW_REASON_SOURCE_INTEGRITY = "source_integrity_failed"
SECURITY_REVIEW_REASON_POLICY_VIOLATION = "policy_violation"
SECURITY_REVIEW_REASON_OPERATOR_QUARANTINE = "operator_quarantine"
SECURITY_REVIEW_REASON_EVALUATION_FIXTURE = "evaluation_fixture"

SOURCE_PROVENANCES = frozenset(
    {
        SOURCE_PROVENANCE_LEGACY,
        SOURCE_PROVENANCE_ADMIN_UPLOAD,
        SOURCE_PROVENANCE_EXTERNAL_URL,
        SOURCE_PROVENANCE_EVALUATION_FIXTURE,
    }
)
SOURCE_TRUST_LEVELS = frozenset({SOURCE_TRUST_TRUSTED, SOURCE_TRUST_EXTERNAL_UNTRUSTED})
SECURITY_REVIEW_STATUSES = frozenset(
    {SECURITY_REVIEW_PENDING, SECURITY_REVIEW_APPROVED, SECURITY_REVIEW_QUARANTINED}
)
QUARANTINE_REASON_CODES = frozenset(
    {
        SECURITY_REVIEW_REASON_PROMPT_INJECTION,
        SECURITY_REVIEW_REASON_SOURCE_INTEGRITY,
        SECURITY_REVIEW_REASON_POLICY_VIOLATION,
        SECURITY_REVIEW_REASON_OPERATOR_QUARANTINE,
    }
)


def security_review_reason_is_valid(*, status: str, reason_code: str) -> bool:
    if status == SECURITY_REVIEW_APPROVED:
        return reason_code == SECURITY_REVIEW_REASON_ADMIN_PASSED
    if status == SECURITY_REVIEW_QUARANTINED:
        return reason_code in QUARANTINE_REASON_CODES
    return False
